#!/usr/bin/env python3
import sys
import os
import time
import RPi.GPIO as GPIO
import datetime

def time_state():
    now = datetime.datetime.now()
    if now.hour > 6 and now.min > 0:
        if now.hour < 19 and now.minute < 30:
            # daytime!
            return True
    else:
        return False
    if now.hour > 19 and now.minute > 30:
            return False
    return False


GPIO.setmode(GPIO.BCM) # GPIO Numbers instead of board numbers

RELAIS_1_GPIO = 23
def relay1(state):
    print(f'relay 1 (pin {RELAIS_1_GPIO}): {state}') 
    if state:
        GPIO.output(RELAIS_1_GPIO, GPIO.HIGH)
    else:
        GPIO.output(RELAIS_1_GPIO, GPIO.LOW)

GPIO.setup(RELAIS_1_GPIO, GPIO.OUT) # GPIO Assign mode

time.sleep(0.1)
# show that it works
relay1(True)
time.sleep(1)
relay1(False)

relay1_state = False
while True:
  time.sleep(5)
  relay1(relay1_state)
  relay1_state = not relay1_state 
